config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "bookmarks/create"
  get "bookmarks/destroy"
  root to: "home#index"
  get "/bookmarks", to: "facilities#bookmark"
  get "/about", to: "fixedpages#about"
  get "/company", to: "fixedpages#company"
  get "/privacy", to: "fixedpages#privacy"
  get "/tos", to: "fixedpages#tos"
  get "/gourmet/:id", to: "facilities#show", as: "gourmet"
  get "/spot/:id", to: "facilities#show", as: "spot"
  get "/gourmets/list", to: "facilities#gourmets_index"
  get "/spots/list", to: "facilities#spots_index"
  get "/gourmet/:facility_id/menus", to: "menus#index", as: "gourmet_menus"
  get "/spot/:facility_id/menus", to: "menus#index", as: "spot_menus"

  # bookmarkのルーティング facilities/bookmarksにルーティング
  resources :facilities, shallow: true do
    # 単数形のメソッドであるresourceとしたのはbookmarkのidが必要ないため。
    # ネスト(入れ子)すると外部キーのboard_idを取得するのが容易
    resource :bookmarks, only: %i[create destroy]
    resources :menus
    get :bookmarks, on: :collection
  end

  # deviseのコントローラーを変更するためのコマンド
  devise_for :users, controllers: {
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # 追加したアクションのルートを定義
  devise_scope :user do
    # パスワード編集のルートを設定
    get "users/edit/password" => "users/registrations#edit_password"
    put "users/update/password" => "users/registrations#update_password"
    # email編集のルートを設定
    get "users/edit/email" => "users/registrations#edit_email"
    put "users/update/email" => "users/registrations#update_email"
    get "users/update/email/confirm" => "users/registrations#update_email_confirm"

    # 新規登録画面
    # プロフィール編集画面（仮登録状態）
    get "before_sign_up", to: "users/registrations#regist"
    # プロフィール編集内容確認画面（仮登録状態）
    post "before_sign_up_confirm", to: "users/registrations#confirm"
    # プロフィール編集内容のアップデート処理（仮登録→本登録に）
    post "before_sign_up_update", to: "users/registrations#registcomp"
  end
  # resource
  resource :user, only: [:show] do
    collection do
      # ここに resourceにない、追加したいメソッドを記入
      # get 'new'
      get "withdraw"
    end
  end
  resources :inquiries, only: %i[new create] do
    collection do
      post "confirm"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/publics/_bottom_area.html.erb
  <div class="bottom row">
    <% if local_assigns[:sns_icon] %>
      <div class=" col-12">
      <div class="sns-title">やんばるスパイク公式SNS</div>
      <div class="sns-icons bottom-sns-area">
          <a href="https://twitter.com/cbper8bitbb5q8d" class="sns-link" target="_blank">
            <%= image_tag('icon_twitter.svg', class:'sns-logo') %>
          </a>
          <a href="https://www.facebook.com/%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BE%E3%82%84%E3%82%93%E3%81[…]3%83%91%E3%82%A4%E3%82%AF-149397135483558/?ref=page_internal" class="sns-link" target="_blank">
            <%= image_tag('icon_fb.svg', class:'sns-logo') %>
          </a>
          <a href="https://www.youtube.com/channel/UCwrDvYey9uKGBeh_l5IF-ag" class="sns-link" target="_blank">
            <%= image_tag('icon_youtube.svg', class:'sns-logo') %>
          </a>
          <a href="https://www.instagram.com/kamizato_programmer/?hl=ja" class="sns-link" target="_blank">
            <%= image_tag('icon_insta.svg', class:'sns-logo') %>
          </a>
          <a href="https://line.me/R/ti/p/%40fyp8311b" class="sns-link" target="_blank">
            <%= image_tag('icon_line.svg', class:'sns-logo') %>
          </a>
      </div>
      </div>
    <% end %>
    <% if local_assigns[:facility_add_request] %>
      <div class="bottom-button col-12">
        <%= link_to "情報掲載依頼はこちら", new_inquiry_path(kind: 1), class:"button button-gradation" %>
      </div>
    <% end %>
    <% if local_assigns[:facility_edit_request] %>
      <div class="bottom-button col-12">
        <%= link_to "情報修正依頼はこちら", new_inquiry_path(kind: 2, facility_id: local_assigns[:facility_id]), class:"button button-gradation" %>
      </div>
    <% end %>
  </div>

app/views/publics/_footer.html.erb
<div class="footer">
  <div class="footer_link">
    <div class="row no-gutters">
      <div class="col-12 row-li">
        <a href ="/about" class="text-white"><p>名護へGOについて</p></a>
      </div>
      <div class="col-6 row-li">
        <a href ="/tos" class="text-white"><p>利用規約</p></a>
      </div>
      <div class="col-6 row-li">
        <a href ="/privacy" class="text-white"><p>プライバシーポリシー</p></a>
      </div>
      <div class="col-6 row-li">
        <a href ="/company" class="text-white"><p>運営会社</p></a>
      </div>
      <div class="col-6 row-li">
        <%= link_to new_inquiry_path(kind: 0) do %>
          <p>問合せ</p>
        <% end %>
      </div>
    </div>
  </div>
  <div class="footer_bottom">
    <p><span>&copy;</span>やんばるスパイク</p>
  </div>
</div>

app/views/publics/_header.html.erb
<div class="fixed-top header">
  <nav class="navbar navbar-expand-md">
    <div class="navbar-toggler menu-icon-area" data-toggle="collapse" data-target=".navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <div class="navbarTogglerDemo01 collapse show collapse-custom-animation">
        <%= image_tag('icon_menu.svg', class:'header-icon') %>
      </div>
      <div class="navbarTogglerDemo01 collapse collapse-custom-animation">
        <%= image_tag('icon_close.svg', class:'header-icon close-icon') %>
      </div>
    </div>
    <div class="logo-area">
        <%= link_to root_path do %>
          <%= image_tag('logo.png', class:'header-logo' ,alt:"名護へGO") %>
        <% end %>
    </div>
    <div class="account-icon-area">
        <% if user_signed_in?	%>
          <%= link_to user_path do %>
            <% if current_user.image.url %>
              <%= image_tag current_user.image.url ,class:"header-user-image" %>
            <% else %>
              <%= image_tag('icon_account.svg', class:'header-icon') %>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do %>
            <%= image_tag('icon_login.svg', class:'header-icon') %>
          <% end %>
        <% end %>
    </div>
    <div class="collapse navbar-collapse navbarTogglerDemo01">
      <ul class="navbar-nav mt-2 mt-md-0">
        <li class="nav-item-header">
          <%= link_to 'グルメ', gourmets_list_path, class: "nav-link" %>
        </li>
        <li class="nav-item-header ">
          <%= link_to '観光スポット', spots_list_path, class: "nav-link" %>
        </li>
        <% if user_signed_in?	%>
          <li class="nav-item-header">
            <%= link_to 'お気に入り', bookmarks_path, class: "nav-link" %>
          </li>
          <li class="nav-item-header">
            <%= link_to '問合せ', new_inquiry_path(kind: 0), class: "nav-link" %>
          </li>
          <li class="nav-item-header">
            <%= link_to 'ログアウト', destroy_user_session_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item-header">
            <%= link_to '問合せ', new_inquiry_path(kind: 0), class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>
<div class="header-space-adjust"></div>