config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "bookmarks/create"
  get "bookmarks/destroy"
  root to: "home#index"
  get "/bookmarks", to: "facilities#bookmark"
  get "/about", to: "fixedpages#about"
  get "/company", to: "fixedpages#company"
  get "/privacy", to: "fixedpages#privacy"
  get "/tos", to: "fixedpages#tos"
  get "/gourmet/:id", to: "facilities#show", as: "gourmet"
  get "/spot/:id", to: "facilities#show", as: "spot"
  get "/gourmets/list", to: "facilities#gourmets_index"
  get "/spots/list", to: "facilities#spots_index"
  get "/gourmet/:facility_id/menus", to: "menus#index", as: "gourmet_menus"
  get "/spot/:facility_id/menus", to: "menus#index", as: "spot_menus"

  # bookmarkのルーティング facilities/bookmarksにルーティング
  resources :facilities, shallow: true do
    # 単数形のメソッドであるresourceとしたのはbookmarkのidが必要ないため。
    # ネスト(入れ子)すると外部キーのboard_idを取得するのが容易
    resource :bookmarks, only: %i[create destroy]
    resources :menus
    get :bookmarks, on: :collection
  end

  # deviseのコントローラーを変更するためのコマンド
  devise_for :users, controllers: {
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # 追加したアクションのルートを定義
  devise_scope :user do
    # パスワード編集のルートを設定
    get "users/edit/password" => "users/registrations#edit_password"
    put "users/update/password" => "users/registrations#update_password"
    # email編集のルートを設定
    get "users/edit/email" => "users/registrations#edit_email"
    put "users/update/email" => "users/registrations#update_email"
    get "users/update/email/confirm" => "users/registrations#update_email_confirm"

    # 新規登録画面
    # プロフィール編集画面（仮登録状態）
    get "before_sign_up", to: "users/registrations#regist"
    # プロフィール編集内容確認画面（仮登録状態）
    post "before_sign_up_confirm", to: "users/registrations#confirm"
    # プロフィール編集内容のアップデート処理（仮登録→本登録に）
    post "before_sign_up_update", to: "users/registrations#registcomp"
  end
  # resource
  resource :user, only: [:show] do
    collection do
      # ここに resourceにない、追加したいメソッドを記入
      # get 'new'
      get "withdraw"
    end
  end
  resources :inquiries, only: %i[new create] do
    collection do
      post "confirm"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end
  # ↓で上書き（デフォルトのコマンドのflashメッセージのみ変更）
  # File 'app/controllers/devise/confirmations_controller.rb', line 22

  def show
    # 会員登録確認後（プロフィールを）のアクション
    self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    yield resource if block_given?
    if resource.errors.empty?
      # ここの部分
      if params[:mail_update] == "1"
        flash[:success] = "メールアドレスの変更が完了しました。"
      else
        flash[:success] = "会員登録が完了しました。"
      end
      sign_in(@user, bypass: true)
      respond_with_navigational(resource) { redirect_to after_confirmation_path_for(resource_name, resource) }
    else
      flash[:alert] = "リンクの有効期限が切れています。ログインできない場合再登録してください"
      redirect_to user_path
    end
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   user_path
  # end
  def after_confirmation_path_for(_resource_name, _resource)
    user_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]
  
    # callback for twitter
    def twitter
      callback_for(:twitter)
    end
  
    # common callback method
    def callback_for(provider)
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.active?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
      else
        redirect_to before_sign_up_path(provider: provider, 
                                        uid: @user.uid)
      end
    end
  
    def failure
      redirect_to root_path
    end

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # パスワード再設定時、ルートにリダイレクトしてしまうのを回避
  prepend_before_action :require_no_authentication, only: [:cancel]
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  def update
    super
  end

  # protected

  def after_resetting_password_path_for(_resource)
    Devise.sign_in_after_reset_password ? new_user_session_path : new_user_session_path
  end

  # パスワード変更メール送信後のパスを設定
  def after_sending_reset_password_instructions_path_for(_resource_name)
    new_user_session_path if is_navigational_format?
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # 上書きすることでresourceがうまく渡せるように（defaultのbefore_actionが原因）
  prepend_before_action :authenticate_scope!, only: %i[edit edit_password edit_email update update_password update_email destroy]
  prepend_before_action :set_minimum_password_length, only: %i[new edit edit_password]
  before_action :configure_sign_up_params, only: [:create]
  before_action :setting_birth_year, only: %i[new edit regist]

  # GET /resource/sign_up
  def new
    build_resource
    yield resource if block_given?
    respond_with resource
  end

  # 仮登録時にプロフィールを編集するアクション
  def regist
    # Oauth(Twitter)認証と、メール認証から来た時と戻るボタンから来た時で場合わけ(paramsが違うため)
    # Oauth認証(Twitter)から編集画面に来たとき
    if params["provider"]
      @user = User.find_by(provider: params["provider"], uid: params["uid"])
      @user.email = nil if @user.has_dummy_email?
    # 確認メールから編集画面に来た時(引数のresourceを使ってユーザーを取得)
    elsif params["resource"]
      @user = User.find(params["resource"])
      # 初回登録か、既に会員登録済みかを場合わけ
      if @user.nickname.present? || @user.prefecture.present? || @user.sex.present? || @user.birth_year.present? || @user.image.present? || @user.profile.present? || @user.mailmagazine.present?
        # 既に会員登録されている場合
        flash[:alert] = "このメールアドレスは既に登録されています。ログインしてください。"
        redirect_to new_user_session_path
      else
        # 初回登録の場合
        @token = params["confirmation_token"]
      end
    # 確認画面から編集画面に戻った時
    elsif params["user"]
      @user = User.find(params["user"]["user_id"])
      @user.nickname = params["user"]["nickname"]
      @user.prefecture = params["user"]["prefecture"]
      @user.sex = params["user"]["sex"]
      @user.birth_year = params["user"]["birth_year"]
      @user.image = params["user"]["image_cache"]
      @user.profile = params["user"]["profile"]
      @user.mailmagazine = params["user"]["mailmagazine"]
      @token = params["user"]["confirmation_token"]
      @user.email = params["user"]["email"] if @user.provider.present?
    end
  end

  # registアクションの内容を表示して確認するアクション
  def confirm
    @user = User.find(params["user"]["user_id"])
    # 初回登録か、既に会員登録済みかを場合わけ
    if @user.nickname.present? || @user.prefecture.present? || @user.sex.present? || @user.birth_year.present? || @user.image.present? || @user.profile.present? || @user.mailmagazine.present?
      # 既に会員登録されている場合
      flash[:alert] = "このメールアドレスでは既に登録されています。ログインしてください。"
      redirect_to new_user_session_path
    else
      # 初回登録の場合
      @user.nickname = params["user"]["nickname"]
      @user.prefecture = params["user"]["prefecture"]
      @user.sex = params["user"]["sex"]
      @user.birth_year = params["user"]["birth_year"]
      @user.image = params["user"]["image"]
      # 選択していない場合でも、キャッシュから復活させる（確認画面から戻る場合を想定）
      if !@user.image.present? && params["user"]["image_cache"].present?
        @user.image.retrieve_from_cache! params["user"]["image_cache"]
      end
      @user.profile = params["user"]["profile"]
      @user.mailmagazine = params["user"]["mailmagazine"]
      @user.email = params["user"]["email"] if @user.provider.present?

      @token = params["confirmation_token"]
      if @user.valid?
        render action: "confirm"
        flash.now[:success] = "確認して完了してください"
      else
        setting_birth_year
        render action: "regist"
        flash.now[:alert] = "失敗しました"
      end
    end
  end

  # プロフィールを保存し、認証トークンを受理することで登録を完了するアクション
  def registcomp
    @user = User.find(params["user"]["user_id"])
    # 初回登録か、既に会員登録済みかを場合わけ
    if @user.nickname.present? || @user.prefecture.present? || @user.sex.present? || @user.birth_year.present? || @user.image.present? || @user.profile.present? || @user.mailmagazine.present?
      # 既に会員登録されている場合
      redirect_to new_user_session_path
      flash[:alert] = "このメールアドレスでは既に登録されています。ログインしてください。"
    else
      # 初回登録の場合
      @user.nickname = params["user"]["nickname"]
      @user.prefecture = params["user"]["prefecture"]
      @user.sex = params["user"]["sex"]
      @user.birth_year = params["user"]["birth_year"]
      @user.image = params["user"]["image_cache"]
      @user.profile = params["user"]["profile"]
      @user.mailmagazine = params["user"]["mailmagazine"]
      @user.email = params["user"]["email"] if @user.provider.present?

      # userのアクティブ状況をactiveに変更
      @user.status = 1
      @token = params["confirmation_token"]
      if @user.valid?
        # Oauth認証の場合、email登録メール不要、認証トークン付与不要
        if @user.provider.present?
          @user.skip_reconfirmation! 
          @user.save
          sign_in_and_redirect @user, event: :authentication
          flash[:success] = "会員登録が完了しました。"
        else
          @user.save
          #  confirmation_pathにuserデータと認証トークンを付与することで本会員登録される
          redirect_to confirmation_path(@user, confirmation_token: @token)
          sign_in(@user, bypass: true)
        end
      else
        render action: "before_create"
        flash.now[:alert] = "会員登録に失敗しました。再登録してください"
      end
    end
  end

  # POST /resource
  def create
    super do # 他はdeviseの機能をそのまま流用する
      #      resource.update(confirmed_at: Time .now.utc)       # Welcomeメールを送信した上で、skip_confirmation!と同一処理を行い自動で認証クローズさせる
      # ↓と同じ意味(登録時にメール認証を行わない設定)
      # resource.skip_confirmation!
      # resource.save

      # deviseは認証済みかどうかの判断をconfirmed_atに日付が入っているかどうかで判定しているようです。
      # そのため、confirmable機能でメールを送信した上で、confirmed_atに値を入れて自己完結させてる
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end
  # passwordを編集
  def edit_password
    @user = current_user
  end

  # email 編集ページのためのメソッド
  def edit_email
    resource
  end

  # updateアクションのデフォルトから引用し変更
  def update_password
    user = current_user
    # 入力した現在のパスワードが有効 かつ 新しいパスワードが以前と同じでないかのフィルター
    if user.valid_password?(update_password_params[:current_password]) && update_password_params[:password] != update_password_params[:current_password]
      user.password = update_password_params[:password]
      user.password_confirmation = update_password_params[:password_confirmation]
      if user.save
        bypass_sign_in(current_user)
        redirect_to user_path
        flash[:success] = "パスワードを更新しました。"
      end
    #  以前と同じパスワードを入力した場合のアクション
    elsif update_password_params[:password] == update_password_params[:current_password]
      clean_up_passwords resource
      redirect_to users_edit_password_path
      flash[:danger] = "新しいパスワードを入力してください"
    # それ以外のエラー時のアクション
    else
      clean_up_passwords resource
      redirect_to users_edit_password_path
      flash[:danger] = "パスワードの更新に失敗しました。"
    end
  end

  def update_email
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?
      if resource.unconfirmed_email.nil?
        flash[:danger] = "メールアドレスを変更してください"
        redirect_to users_edit_email_path
      else
        redirect_to users_update_email_confirm_path(unconfirmed_email: resource.unconfirmed_email)
      end
    else
      flash[:danger] = "メールアドレスの更新に失敗しました"
      redirect_to users_edit_email_path
    end
  end

  def update_email_confirm
    @unconfirmed_email = params[:unconfirmed_email]
  end
  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # def temp
  #   @user = params["resource"]
  # end

  protected

  # 更新（編集の反映）時にパスワード入力を省く
  def update_resource(resource, params)
    if params[:password].blank? && params[:password_confirmation].blank? && params[:current_password].blank?
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  # 更新後のパスを指定
  def after_update_path_for(_resource)
    user_path
  end

  # password変更時のparamsを読み込む
  def update_password_params
    params.require(:user).permit(:attribute, :password, :password_confirmation, :current_password)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def setting_birth_year
    @birth_year = []
    for year in (1950..DateTime.now.year).reverse_each do
      @birth_year << year
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(current_user.id)
    @spots = current_user.bookmark_facilities.includes(:user).where(type: "spot").page(params[:page])
    @gourmets = current_user.bookmark_facilities.includes(:user).where(type: "gourmet").page(params[:page])

    return unless request.xhr?

    case params[:type]
    # when "spot", "gourmet"
      # render params[:type].to_s
    when "bookmark_spot", "bookmark_gourmet"
      @bookmark_type = params[:type]
      render 'facilities/bookmark'
    end
  end

  def withdraw; end
end

app/helpers/users_helper.rb
module UsersHelper
  def calculation_of_age(birth_year)
    return "10歳未満" if Date.today.year.to_i - birth_year < 10
    decades = (Date.today.year.to_i - birth_year) / 10
    if (Date.today.year.to_i - birth_year) % 10 < 5
      return "#{decades}0代前半"
    else
      return "#{decades}0代後半"
    end
  end
end

app/views/users/show.html.erb
<%= content_for(:title, "マイページ") %>

<!-- マイページ-->
<div class="list-body">
  <!-- プロフィール -->
  <div class="user-top container">
    <div class="row">
      <div class="user-lists">
        <div class="list-content">
          <% if @user.image.url %>
          <%= image_tag @user.image.url ,class:"user-image"%>
          <% else %>
          <%= image_tag "no-image.png" ,class:"non-user-image" %>
          <% end %>
        </div>
        <div class="list-content">
          <h3><%=@user.nickname%></h3>
          <!-- 誕生日から年齢を計算 -->
          <% if @user.birth_year.to_i > 0 %>
            <p class="show-content" ><%=  calculation_of_age(@user.birth_year.to_i) %></p>
          <% end %>
          <p class="show-content"><%=@user.sex_i18n%></p>
          <p class="show-content"><%=@user.prefecture%></p>
        </div>

        <!-- 切り替えボタンの設定 -->
        <div class="user-icon list-content " data-toggle="modal" data-target="#exampleModal"><i class="fas fa-user-edit "></i></div>

        <!-- モーダルの設定 -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                  <span class="cross-mark" aria-hidden="true">&times;</span>
                </button>
              </div>
              <!-- ここからリンクを編集 -->
              <div class="modal-body">
                <%= link_to  "プロフィールを編集", edit_user_registration_path %>
              </div>
              <div class="modal-body">
                <%= link_to  "メールアドレス変更", users_edit_email_path %>
              </div>
              <div class="modal-body">
                <%= link_to  "パスワード変更", users_edit_password_path %>
              </div>
              <div class="modal-body">
                <%= link_to  "退会手続きへ", withdraw_user_path   %>
              </div>
              <div class="modal-footer">
              </div><!-- /.modal-footer -->
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
      </div>
    </div>
    <div class="profile text-left"><%= simple_format(@user.profile) %></div>
  </div>

<!-- タブのデザイン ================================================================= -->

  <!-- タブ -->
  <div>
    <!-- タブの表示設定 -->
    <div class="tabs row">
      <input id="gourmet" type="radio" name="tab_item" checked>
      <label class="tab_item" for="gourmet">グルメ</label>

      <input id="spot" type="radio" name="tab_item">
      <label class="tab_item" for="spot">スポット</label>

    <div class="tab_content list-wrapper" id="gourmet_content">
      <div class="row" id="gourmet_lists">
       <% if @gourmets.present?%>
          <%= render partial: 'facilities/facilities_list', collection: @gourmets, as: 'facility' %>
        <% else %>
          <div class="non_tab_text">
            <p>お気に入りされたグルメはありません。</p>
          </div>
        <% end %>
      </div>

      <div class="list-button col-12">
        <%= link_to_next_page @gourmets, 'もっと見る', remote: true , params: { type: :bookmark_gourmet },
        class:"more button button-blue-border" ,type:"button" ,id:'gourmet_view_more'%>
      </div>
    </div>  <!-- tab_content -->

    <div class="tab_content list-wrapper" id="spot_content">
      <div class="row" id="spot_lists">
        <% if @spots.present?%>
          <%= render partial: 'facilities/facilities_list', collection: @spots, as: 'facility' %>
        <% else %>
          <div class="non_tab_text">
            <p>お気に入りされたスポットはありません。</p>
          </div>
        <% end %>
      </div>
      <div class="list-button col-12">
        <%= link_to_next_page @spots, 'もっと見る', remote: true , params: { type: :bookmark_spot },
        class:"more button button-blue-border" ,type:"button" ,id:'spot_view_more'%>
      </div>

    </div> <!-- tab_content -->
   </div> <!-- tabs -->
  </div>  <%# container %>
</div>    <%# list-body %>

app/views/users/withdraw.html.erb
<%= content_for(:title, "退会手続き") %>

<div class="login-area">
  <div class="list-title underline-blue">
    <h1>退会手続き</h1>
  </div>
  <p class="text-center mt-3">退会されますと、これまでのお客様のデータは削除され復元できなくなる可能性があります</p>
  <!-- Button trigger modal -->
  <button type="button" class="button button-blue-color" data-toggle="modal" data-target="#exampleModal">退会する</button>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">退会処理</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          本当に退会しますか？
        </div>
        <div class="modal-footer">
          <%= link_to  "はい", user_registration_path, method: :delete ,type:"button" ,class:"button button-blue-color" %>
          <button type="button" class="button button-gray-color" data-dismiss="modal">いいえ</button>
        </div>
      </div>
    </div>
  </div>
</div>