config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "bookmarks/create"
  get "bookmarks/destroy"
  root to: "home#index"
  get "/bookmarks", to: "facilities#bookmark"
  get "/about", to: "fixedpages#about"
  get "/company", to: "fixedpages#company"
  get "/privacy", to: "fixedpages#privacy"
  get "/tos", to: "fixedpages#tos"
  get "/gourmet/:id", to: "facilities#show", as: "gourmet"
  get "/spot/:id", to: "facilities#show", as: "spot"
  get "/gourmets/list", to: "facilities#gourmets_index"
  get "/spots/list", to: "facilities#spots_index"
  get "/gourmet/:facility_id/menus", to: "menus#index", as: "gourmet_menus"
  get "/spot/:facility_id/menus", to: "menus#index", as: "spot_menus"

  # bookmarkのルーティング facilities/bookmarksにルーティング
  resources :facilities, shallow: true do
    # 単数形のメソッドであるresourceとしたのはbookmarkのidが必要ないため。
    # ネスト(入れ子)すると外部キーのboard_idを取得するのが容易
    resource :bookmarks, only: %i[create destroy]
    resources :menus
    get :bookmarks, on: :collection
  end

  # deviseのコントローラーを変更するためのコマンド
  devise_for :users, controllers: {
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  # 追加したアクションのルートを定義
  devise_scope :user do
    # パスワード編集のルートを設定
    get "users/edit/password" => "users/registrations#edit_password"
    put "users/update/password" => "users/registrations#update_password"
    # email編集のルートを設定
    get "users/edit/email" => "users/registrations#edit_email"
    put "users/update/email" => "users/registrations#update_email"
    get "users/update/email/confirm" => "users/registrations#update_email_confirm"

    # 新規登録画面
    # プロフィール編集画面（仮登録状態）
    get "before_sign_up", to: "users/registrations#regist"
    # プロフィール編集内容確認画面（仮登録状態）
    post "before_sign_up_confirm", to: "users/registrations#confirm"
    # プロフィール編集内容のアップデート処理（仮登録→本登録に）
    post "before_sign_up_update", to: "users/registrations#registcomp"
  end
  # resource
  resource :user, only: [:show] do
    collection do
      # ここに resourceにない、追加したいメソッドを記入
      # get 'new'
      get "withdraw"
    end
  end
  resources :inquiries, only: %i[new create] do
    collection do
      post "confirm"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/facility.rb
class Facility < ApplicationRecord

belongs_to :user, foreign_key: "owner_id"
has_many :menus
has_many :facility_images


#bookmarks 中間テーブルの設定
has_many :bookmarks,dependent: :destroy
# facilityのお気に入り判定 → views側で呼び出し
def bookmark_by?(user)
  bookmarks.where(user_id: user.id).exists?
end

# genres 中間テーブルの設定
has_many :facility_genres, dependent: :destroy
has_many :genres, through: :facility_genres
# 以下のコマンドでfacilitiesとgenresのどちらかを編集したときにもう片方も反映させる
accepts_nested_attributes_for :facility_genres, allow_destroy: true



# typeカラムは本来使えないが、使える様にするコマンド
self.inheritance_column = :_type_disabled
# typeをenumで定義
enum type:{spot: 0,gourmet:1}
validates :type, presence:  true
validates :name, presence:  true
validates :postal_code, presence: true
validates :address, presence: true
validates :description, presence: true
validates :parking, presence: true
validates :owner_id, presence: true
enum status: {open: 0, closed_shop: 1, closing_down: 2, will_open: 3}
validates :created_user, presence: true
validates :updated_user, presence: true

# page nationの表示数を設定（もっと見るボタンを押す前）
paginates_per 10
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  # 詳細表示
  def show
    @facility = Facility.includes(:facility_images).find(params[:id])
  end

  # 一覧表示
  def spots_index
    @facility_type = "spot"
    @facilities = Facility.includes(:facility_images).where(type: @facility_type).page(params[:page])
    render :index
  end

  def gourmets_index
    @facility_type = "gourmet"
    @facilities = Facility.includes(:facility_images).where(type: @facility_type).page(params[:page])
    render :index
  end


  def bookmark
    # has many throughのりレーションを組んだことで　current_user.bookmark_facilitiesで呼
    @spots = current_user.bookmark_facilities.includes(:user).where(type: "spot").page(params[:page])
    @gourmets = current_user.bookmark_facilities.includes(:user).where(type: "gourmet").page(params[:page])

    # もっとみるボタンの非同期処理　場合わけ（施設とグルメ）
    # 同じページに二つの「もっとみるボタン」があるため、場合わけが必要
    return unless request.xhr?
    case params[:type]
    when "bookmark_spot", "bookmark_gourmet"
      @bookmark_type = params[:type]
      # render params[:type].to_s
    end
  end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_bookmark.html.erb
<%= link_to facility_bookmarks_path(facility.id), method: :delete , remote: true , id:"js-bookmark-button-for-facility-#{facility.id}", class:"favorite-icon" do %>
  <%= icon('fas', 'heart')  %>
  &nbsp;
  <%= facility.bookmarks.count %>
<% end %>

app/views/facilities/_bookmark_area.html.erb
<% if facility.bookmark_by?(current_user) %>
<%= render 'facilities/bookmark', facility: facility %>
<% else %>
<%= render 'facilities/unbookmark', facility: facility %>
<% end %>

app/views/facilities/_bookmark_for_detail.html.erb
<object>
  <% if facility.bookmark_by?(current_user) %>
  <%= link_to icon('fas', 'heart'), facility_bookmarks_path(facility.id,flag:true), method: :delete , remote: true , id:"js-bookmark-button-for-facility-#{facility.id}", class:"icon-red" %>
  <div class="detail-bookmark-count">
    <%= facility.bookmarks.count %>
  </div>
  <% else %>
  <%= link_to icon('far', 'heart'), facility_bookmarks_path(facility.id,flag:true), method: :post , remote: true ,  id:"js-bookmark-button-for-facility-#{facility.id}", class:"icon-red" %>
  <div class="detail-bookmark-count">
    <%= facility.bookmarks.count %>
  </div>
  <% end %>
</object>

app/views/facilities/_bookmark_for_detail2.html.erb
<% if facility.bookmark_by?(current_user) %>
<%= link_to icon('fas', 'heart'), facility_bookmarks_path(facility.id,flag:true), method: :delete , remote: true , id:"js-bookmark-button-for-facility-#{facility.id}", class:"icon-red detail-bookmark-2" %>
<% else %>
<%= link_to icon('far', 'heart'), facility_bookmarks_path(facility.id,flag:true), method: :post , remote: true ,  id:"js-bookmark-button-for-facility-#{facility.id}", class:"icon-red detail-bookmark-2" %>
<% end %>

app/views/facilities/_facilities_list.html.erb
<div class="col-6 col-lg-3 show-row-list">
  <% if facility.type == "gourmet" %>
    <% url = gourmet_path(facility.id) %>
  <% else %>
    <% url = spot_path(facility.id) %>
  <% end %>
  <%= link_to url, class:"a-card" do %>
    <div class="card">
      <% images = facility.facility_images.first%>
      <% if images.present? %>
        <%= image_tag(images.image.thumb.url ,class:"card-img-top" ,alt:"...") %>
      <% else %>
        <%= image_tag("no-image-facility.png" ,class:"card-img-top" ,alt:"...") %>
      <% end %>
      <div class="card-body">
        <h4 class="card-title"><%= facility.name %></h4>
        <p class="card-text"><%= facility.description %></p>
        <% if user_signed_in? %>
        <div class="bookmark_btn_<%= facility.id %> favorite-area" data-bookmark='1'>
          <object><%= render 'facilities/bookmark_area', facility: facility %></object>
        </div>
        <% else%>
        <div class="favorite-area">
          <object ect>
            <%= link_to new_user_session_path, class:"icon-red" do %>
              <%= icon('far', 'heart') %>
              &nbsp;
              <%= facility.bookmarks.count %>
            <% end %>
          </object>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/facilities/_unbookmark.html.erb
<%= link_to facility_bookmarks_path(facility.id), method: :post , remote: true , id:"js-bookmark-button-for-facility-#{facility.id}", class:"favorite-icon" do %>
  <%= icon('far', 'heart')  %>
  &nbsp;
  <%= facility.bookmarks.count %>
<% end %>

app/views/facilities/bookmark.html.erb
<%= content_for(:title, "お気に入り") %>

<% if ( @gourmets.empty? && @spots.empty? ) %>
  <p class="text-center mt-5">現在お気に入りに登録している、グルメ・観光スポットはありません。</p>
<% end %>
<% unless @gourmets.empty? %>
<section class="list-body row">
  <div class="list-title underline-blue">
    <h1>グルメ</h1>
  </div>
  <div class="list-wrapper col-12">
    <div class="row " id="gourmet_lists">
      <%= render partial: 'facilities/facilities_list', collection: @gourmets, as: 'facility' %>
    </div>
      <div class="list-button col-12">
        <%= link_to_next_page @gourmets, 'もっと見る', remote: true , params: { type: :bookmark_gourmet },
      class:"button button-blue-border" ,id:'gourmet_view_more'%>
      </div>
  </div>
</section>
<% end %>

<% unless @spots.empty? %>
<section class="list-body row">
  <div class="list-title underline-blue">
    <h1>観光スポット</h1>
  </div>
  <div class="list-wrapper col-12">
    <div class="row " id="spot_lists">
      <%= render partial: 'facilities/facilities_list', collection: @spots, as: 'facility' %>
    </div>
      <div class="list-button col-12">
        <%= link_to_next_page @spots, 'もっと見る', remote: true , params: { type: :bookmark_spot },
      class:"button button-blue-border" ,id:'spot_view_more'%>
      </div>
  </div>
</div>
</section>
<% end %>

app/views/facilities/bookmark.js.erb
//もっとみるボタン（施設）の非同期処理
<% if @bookmark_type == "bookmark_gourmet" %>
  <% puts "bookmark_gourmet: #{@bookmark_type}" %>
  $('#gourmet_lists').append("<%= escape_javascript(render partial: 'facilities/facilities_list',  collection: @gourmets, as: 'facility') %>");
  $("#gourmet_view_more").replaceWith("<%= escape_javascript(link_to_next_page(@gourmets, 'もっと見る', remote: true, id: 'gourmet_view_more', class:"button button-blue-border")) %>");
<% else %>
  <% puts "bookmark_spot: #{@bookmark_type}"  %>
  $('#spot_lists').append("<%= escape_javascript(render partial: 'facilities/facilities_list',  collection: @spots, as: 'facility') %>");
  $("#spot_view_more").replaceWith("<%= escape_javascript(link_to_next_page(@spots, 'もっと見る', remote: true, id: 'spot_view_more', class:"button button-blue-border")) %>");
<% end %>

app/views/facilities/index.html.erb
<% if @facility_type == "gourmet" %>
  <% type_text = "グルメ" %>
<% else %>
  <% type_text = "観光スポット" %>
<% end %>

<%= content_for(:title, "おすすめ"+type_text.to_s) %>


<div class="list-body row">
  <div class="list-title underline-blue">
    <h1>名護のおすすめ<%= type_text.to_s %></h1>
  </div>
  <div class="list-wrapper col-12">
    <div class="row " id="facility_lists">
      <%= render partial: 'facilities/facilities_list', collection: @facilities, as: 'facility' %>
    </div>
    <div class="list-button">
      <%= link_to_next_page @facilities, "おすすめ#{type_text.to_s}をもっとみる", remote: true, class:"button button-blue-border" ,id:'view_more'%>
    </div>
  </div>
</div>
<%= render partial: "publics/bottom_area", locals: {sns_icon: true, facility_add_request: true } %>

app/views/facilities/index.js.erb
$('#facility_lists').append("<%= escape_javascript(render partial: 'facilities/facilities_list',  collection: @facilities, as: 'facility') %>");
<% if @facility_type == "gourmet" %>
$("#view_more").replaceWith("<%= escape_javascript(link_to_next_page(@facilities, 'おすすめグルメをもっとみる', remote: true, class:"button button-blue-border" ,id:'view_more')) %>");
<% else %>
$("#view_more").replaceWith("<%= escape_javascript(link_to_next_page(@facilities, 'おすすめ観光スポットをもっとみる', remote: true, class:"button button-blue-border" ,id:'view_more')) %>");
<% end %>

app/views/facilities/show.html.erb
<%= content_for(:title, @facility.name) %>
<%= content_for(:description, @facility.description) %>
<%= content_for(:image_url, @facility.facility_images.first&.image&.url) %>

<!-- 詳細画面 -->
<div class="detail-wrapper detail-width">
  <!-- トップ -->
  <div class="detail-top">
      <% images = @facility.facility_images.first%>
      <% if images.present? %>
        <%= image_tag(images.image.url ,class:"facility-main-width card-img-max-height fit-image" ,alt:"...")  %>
      <% else %>
        <%= image_tag("no-image-facility.png" ,class:"facility-main-width card-img-max-height fit-image" ,alt:"...") %>
      <% end %>
    <h2 class="detail-title"><%= @facility.name%></h2>
    <!-- いいねボタン -->
    <!-- ログインの有無で場合わけ -->
    <% if user_signed_in? %>
    <div class="bookmark_btn_<%= @facility.id %>  favorite-area detail-bookmark-icon icon-red" data-bookmark='1'>
      <!-- ここ専用のパーシャル -->
      <%= render 'facilities/bookmark_for_detail', {facility: @facility,gourmet: @gourmet} %>
    </div>
    <% else%>
    <div class="favorite-area detail-bookmark-icon">
      <!-- ②ここはパーシャルを使用 -->
      <object><%= link_to icon('far', 'heart'), new_user_session_path, class:"icon-red" %></object>
      <div class="detail-bookmark-count">
        <%= @facility.bookmarks.count %>
      </div>
    </div>
    <% end %>
    <!-- いいねボタンここまで -->
    <!-- いいねボタン(画面右下固定) -->
    <!-- ログインの有無で場合わけ -->
    <% if user_signed_in? %>
    <div class="bookmark_btn_<%= @facility.id %> favorite-area fixed-bookmark icon-red" data-bookmark='2'>
      <!-- ここ専用のパーシャル -->
      <%= render 'facilities/bookmark_for_detail2', {facility: @facility,gourmet: @gourmet} %>
    </div>
    <% else%>
    <div class="favorite-area fixed-bookmark">
      <!-- ②ここはパーシャルを使用 -->
      <object><%= link_to icon('far', 'heart'), new_user_session_path, class:"icon-red" %></object>
    </div>
    <% end %>
    <!-- いいねボタン(画面右下固定)ここまで -->
  </div>
  <%= @facility.description %>
  <div class="list-title underline-blue advice-margin">
    <h1>おすすめポイント</h1>
  </div>
  <div class = "menu-margin-bottom">
    <%= @facility.advice %>
  </div>
  <div class="menu text-center">
  <%if @facility.menus[0] %>
    <div class="list-title underline-blue menu-margin">
      <h1>メニュー</h1>
    </div>

    <!-- メニュー一覧表示 -->
    <div class="list-wrapper">
      <div class="row " id="menu_lists">
        <!-- アクセス元から表示するメニューの上限数を決定 PC:3, MOBILE:2 -->
        <% if request.env['HTTP_USER_AGENT'].include? "Mobile" %>
          <% maxnum = MOBILE_MENUS_MAX %>
        <% else %>
          <% maxnum = PC_MENUS_MAX %>
        <% end %>
        <% for num in 0..maxnum-1 do %>
          <% if @facility.menus[num] %>
          <div class="col-6 col-sm-6 col-lg-4 show-row-list">
            <div class="card ">
              <%= image_tag(@facility.menus[num].image.thumb.url, class:"card-img-top" ,alt:"...") %>
              <div class="card-body list-cd">
                <h5 class="card-title"><%= @facility.menus[num].name %></h5>
                <p class="card-text"><%= @facility.menus[num].content %></p>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <!-- メニュー一覧表示(slick) -->
<!--    <div class="sliderArea">
      <div class="full-screen-o slider">
        <% for num in 0..PC_MENUS_MAX-1 do %>
          <% if @facility.menus[num] %>
          <div class="card heightLine">
            <%= image_tag(@facility.menus[num].image.thumb.url ,class:"card-img-top" ,alt:"...") %>
            <div class="card-body list-cd">
              <h5 class="card-title"><%= @facility.menus[num].name %></h5>
              <p><%= @facility.menus[num].content %></p>
            </div>
          </div>
          <%end%>
        <%end%>
      </div>
    </div> -->
    <div class="list-button menu-margin-top">
      <%= link_to  "メニューをもっとみる", facility_menus_path(@facility.id)  ,type:"button", class:"button button-blue-border button-arrow" %>
    </div>
    <%end%>
    <div class="shop-information">
      <ul class="information-lists">
        <li class="information-list">
          <p class="information-list-title">住所</p>
          <p class="information-list-content"><%= @facility.address %></p>
        </li>
        <li class="information-list">
          <p class="information-list-title">アクセス</p>
          <p class="information-list-content"><%= @facility.running_time %></p>
        </li>
        <li class="information-list">
          <p class="information-list-title">TEL</p>
          <% if @facility.tel %>
            <p class="information-list-content"><%= link_to( @facility.tel, "tel:" + @facility.tel ) %></p>
          <% end %>
        </li>
        <li class="information-list">
          <p class="information-list-title">営業時間</p>
          <p class="information-list-content"><%= @facility.opening_hours %></p>
        </li>
        <li class="information-list">
          <p class="information-list-title">定休日</p>
          <p class="information-list-content"><%= @facility.holiday %></p>
        </li>
        <li class="information-list">
          <p class="information-list-title">駐車場</p>
          <p class="information-list-content"><%= @facility.parking %></p>
        </li>
        <li class="information-list">
          <p class="information-list-title">ホームページ</p>
          <p class="information-list-content"><%= link_to(@facility.name, @facility.home_page, target: :_blank) %></p>
        </li>
      </ul>
    </div>
    <div class="google-map text-center">
<!--      <div class="w-100" id="map" data-facility-latitude="<%= @facility.latitude %>" data-facility-longitude="<%= @facility.longitude %>">google map</div> -->
        <iframe src="https://maps.google.co.jp/maps?output=embed&q=<%= @facility.name %> <%= @facility.address %>&z=16" class="w-100" id="map" frameborder="0" scrolling="no" ></iframe>
    </div>
  </div>
</div>
<%= render partial: "publics/bottom_area", locals: {sns_icon: true, facility_edit_request: true, facility_id: @facility.id } %>

<!-- google mapを呼び出すjavascript -->
<script>
  var e = document.getElementById('map');
  var latitude = Number(e.getAttribute('data-facility-latitude'));
  var longitude = Number(e.getAttribute('data-facility-longitude'));

  function initMap() {
    geocoder = new google.maps.Geocoder()
    // console.log(latitude)
    // console.log(longitude)
    // console.log(e)
    let map = new google.maps.Map(document.getElementById('map'), {
      center: {
        lat: latitude,
        lng: longitude
      },
      zoom: 16,
    });

    marker = new google.maps.Marker({
      position: {
        lat: latitude,
        lng: longitude
      },
      map: map
    });
  }
  window.google = {};
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap" async defer></script>

<!-- slickを呼び出すJavascript -->
<script>
  $(function(){
    $(".full-screen-o").not('.slick-initialized').slick({
      centerMode: true, // スライドを中心に表示して部分的に前後のスライドが見えるように設定（奇数番号のスライドに使用）
      centerPadding: '28%', // センターモード時のサイドパディング。見切れるスライドの幅。’px’または’％’。
      dots: true, // ドットインジケーターの表示
      autoplay: true, // 自動再生を設定
      autoplaySpeed: 3000, // 自動再生のスピード（ミリ秒単位）
      speed: 1000, // スライド/フェードアニメーションの速度を設定
      infinite: true, // スライドのループを有効にするか
    });
  });
</script>

app/views/facilities/show.js.erb
$('#facility_lists').append("<%= escape_javascript(render 'facilities/facility_list', object: @facilities) %>");
$("#view_more").replaceWith("<%= escape_javascript(link_to_next_page(@facilities, 'もっと見る', remote: true, id: 'view_more')) %>");

app/views/facilities/show_facilities.js.erb
$('#facility_lists').append("<%= escape_javascript(render partial: 'facilities/facilities_list',  collection: @facilities, as: 'facility') %>");
<% if @facility_type == "gourmet" %>
$("#view_more").replaceWith("<%= escape_javascript(link_to_next_page(@facilities, 'おすすめグルメをもっと見る', remote: true, class:"button button-blue-border" ,id:'view_more')) %>");
<% else %>
$("#view_more").replaceWith("<%= escape_javascript(link_to_next_page(@facilities, '観光スポットをもっと見る', remote: true, class:"button button-white-border" ,id:'view_more')) %>");
<% end %>